[default]
LOG_CONFIG = "./logging.conf"
DATABASE_URL = "postgresql://postgres:example@localhost:5432/postgres"
MQTT_BROKER_HOST = "public.mqtthq.com"
MQTT_BROKER_PORT = 1883
MQTT_TOPIC = "image-topic"
PORT = 5000
RELOAD = true
